#!/bin/bash

# Reset rules
iptables		-F
iptables		-X
iptables -t nat		-F
iptables -t nat		-X
iptables -t mangle	-F
iptables -t mangle	-X

# Drop everything as default behavior
iptables -P INPUT	DROP
iptables -P OUTPUT	DROP
iptables -P FORWARD 	DROP

# Loopback
iptables -A INPUT	-i lo						-j ACCEPT
iptables -A OUTPUT	-o lo						-j ACCEPT

# DNS
iptables -A OUTPUT	-p tcp		--dport	53			-j ACCEPT
iptables -A OUTPUT	-p udp		--dport	53			-j ACCEPT

# SSH
iptables -A INPUT	-p tcp		--dport	2222			-j ACCEPT

# HTTP
iptables -A OUTPUT 	-p tcp		--dport	80			-j ACCEPT

# HTTPS
iptables -A OUTPUT	-p tcp		--dport	443			-j ACCEPT

# Outgoing ping
iptables -A OUTPUT	-p icmp		--icmp-type echo-request	-j ACCEPT
iptables -A INPUT	-p icmp		--icmp-type echo-reply		-j ACCEPT

# Already established connections
iptables -A INPUT	-m conntrack	--ctstate ESTABLISHED,RELATED	-j ACCEPT
iptables -A OUTPUT	-m conntrack	--ctstate ESTABLISHED,RELATED	-j ACCEPT
