#!/bin/bash

# Flush iptables
iptables -F
iptables -X
iptables -t nat -F
iptables -t nat -X
iptables -t mangle -F
iptables -t mangle -X

# Drop everything as default behavior
iptables -P INPUT DROP
iptables -P OUTPUT DROP
iptables -P FORWARD DROP

# Allows SSH connections
iptables -A INPUT -p tcp -i enp0s3 --dport 2222 -j ACCEPT

# Allows HHTP and HTTPS connections
iptables -A INPUT -p tcp -i enp0s3 --dport 80 -j ACCEPT
iptables -A INPUT -p tcp -i enp0s3 --dport 443 -j ACCEPT

# Allows all loopback traffic
iptables -I INPUT -i lo -j ACCEPT

# Allows traffic with an already opened connection
iptables -A INPUT -m conntrack --ctstate ESTABLISHED -j ACCEPT
iptables -A OUTPUT -m conntrack --ctstate ESTABLISHED -j ACCEPT